image: Visual Studio 2019
before_build:
- choco install opencover
build_script:
- dotnet build
test_script:
- C:\Users\AppVeyor\AppData\Local\Apps\OpenCover\OpenCover.Console.exe -register:Path32 -target:"dotnet" -targetargs:"test"  -output:coverage.xml -returntargetcode
after_test:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "coverage.xml" -U "-s" -A "-s"
artifacts:
  - path: CanoePoloLeagueOrganiser\*.nupkg
