image: Visual Studio 2017
before_build:
- choco install opencover
- nuget restore
build:
  project: CanoePoloLeagueOrganiser.sln
after_build:
- cd CanoePoloLeagueOrganiser
- nuget pack -symbols
- cd ..
test_script:
- OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:"CanoePoloLeagueOrganiserTests\bin\Debug\CanoePoloLeagueOrganiserTests.dll -noshadow -appveyor"  -output:coverage.xml -returntargetcode
after_test:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "coverage.xml"
artifacts:
  - path: CanoePoloLeagueOrganiser\*.nupkg
