image: Visual Studio 2017
environment:
  SONARQUBE_TOKEN:
    secure: qdGKfgHYg4+g2UpIhNRAE61rwGtm0vDLC9pUAxxDW66IiER7WLW5p4KiOxqVSjZX
before_build:
- choco install "msbuild-sonarqube-runner" -y
- choco install opencover
- nuget restore
- SonarQube.Scanner.MSBuild.exe begin /k:"cuddlyburger.canoe-polo-league-organiser-backend" /d:"sonar.host.url=https://sonarcloud.io" /d:"sonar.organization=ceddlyburge-github" /d:"sonar.login=%SONARQUBE_TOKEN%"
build:
  project: CanoePoloLeagueOrganiser.sln
after_build:
- SonarQube.Scanner.MSBuild.exe end /d:"sonar.login=%SONARQUBE_TOKEN%"
- cd CanoePoloLeagueOrganiser
- nuget pack -symbols
- cd ..
test_script:
- OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:"CanoePoloLeagueOrganiserTests\bin\Debug\CanoePoloLeagueOrganiserTests.dll -noshadow -appveyor"  -output:coverage.xml -returnTargetErrorCode
after_test:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "coverage.xml"
artifacts:
  - path: CanoePoloLeagueOrganiser\*.nupkg
